project:
  type: website

website:
  title: "Temi"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: content/index.qmd
        text: Blog
      # - href: about.qmd
      #   text: About

  page-navigation: true

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

execute:
  freeze: auto  # re-render only when source changes

markdown: kramdown

