---
title: ""
# listing:
#   sort: "date desc"
#   type: default
#   categories: false
#   sort-ui: false
#   filter-ui: false
page-layout: full
title-block-banner: false
---

> Just so you know, I don't necessarily endorse all of these books.

## <ins>currently reading</ins>
- The Second Sex by Simone de Beauvoir 
  : Started sometime in August 2023

## <ins>previously read</ins>

there's more, but in no particular order:

- Factotum by Charles Bukowski
- In the Country of Men by Matar Hisham
- The Secret Lives of Baba Segi's Wives by Lola Shoneyin
- The God of Small Things by Arundhati Roy
- A Peace To End All Peace by David Fromkin
- A Song of Ice and Fire by George R. R. Martin
  - A Game of Thrones
  - A Clash of Kings
  - A Storm of Swords
- The Emperor of All Maladies by Siddhartha Mukherjee
- Then We Came To The End by Joshua Ferris
- Animal's People by Indra Sinha
- Never Let Me Go by Kazuo Ishiguro
- The Buried Giant by Kazuo Ishiguro
- The First Law by Joe Abercrombie
  - The Blade Itself
  - Before They Are Hanged
- Anansi Boys by Neil Gaiman
- Future Popes of Ireland by Darragh Martin
