{
  "hash": "aad4e9703377b67f80c2303ba8aecf01",
  "result": {
    "markdown": "---\ntitle: \"Simulating discrete and continuous populations\"\nauthor: \"Temi\"\ndate: \"May 13 2022\"\nhtml:\n    code-fold: true\n---\n\n\n### **I'm still working on this**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(gtools)\n```\n:::\n\n\n## Introduction\nOftentimes, we want to simulate populations in order to do some analysis. In this demo, I go over a, perhaps, crude way to mimic discrete and continuous populations. Before simulating, we need to know what a population is. In genetics, a population is a grouping of individuals based on some similarity in allele frequencies between them. Of course, there are many other definitions of what a population is. In this demo, I will use the definition based on allele frequencies. \n\nOne way to generate allele frequencies that mimic that seen in typical populations is to use the $F_{ST}$, AKA the fixation index, AKA F-statistic. $F_{ST}$ measures population differentiation as a result of genetic structure. Values range between 0 and 1, and higher values mean that two populations are highly similar. There are many definitions of $F_{ST}$, depending on what you are discussing - and I am still learning about most of them. In this case, however, I am primarily concerned with allele frequency-related definitions. \n\n\n### Simulating discrete populations\nTo simulate populations based on the definition of $F_{ST}$, one thing we can do is to simulate an ancestral population's allele frequencies. This is similar to having a founder population from which every other population descends. Afterwards, we can simulate different populations from this ancestral population. This follows from the [Balding-Nichols model](https://en.wikipedia.org/wiki/Balding%E2%80%93Nichols_model). \n\n\\begin{align}\nBeta(\\frac{1-F}{F}p, \\frac{1-F}{F}(1-p))\n\\end{align}\n\nAssume that we have 500 alleles/loci, and 4 populations, and we intend to simulate 1000 individuals from each of these populations. We can define our $F_{ST}$ to be, say, 0.09 between populations 1 and 2, 0.19 between populations 1 and 2, and population 3, and 0.4 between all these populations, and population 4. Therefore, populations 1 and 2 will be closely related, and different from population 3, and all of them will be different from population 4.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nM <- 500 # number of alleles or SNPs\nn_pops <- 4 # number of populations\nN <- 1000 # 20 individuals in each n_pops\nf_pop12 <- 0.09\nf_pop3 <- 0.19 # a third, distant, unrelated population\nf_pop4 <- 0.4 # a fourth population\n```\n:::\n\n\nWhen we make plots of the allele frequencies of these populations, we expect high correlations between populations 1 and 2, and not-so-high correlations when we compare with the other populations 3 and 4. \n\nWe can generate some random minor allele frequencies (MAFs) to be the ancestral allele frequencies, and generate independent draws from the distribution of the ancestral allele frequencies, based on the equation above. \n\n::: {.cell}\n\n```{.r .cell-code}\nancestral_allele_freqs <- runif(M, 0.01, 0.5)\nsh1 <- ((1-f_pop12)/f_pop12)*ancestral_allele_freqs\nsh2 <- ((1-f_pop12)/(f_pop12))*(1-ancestral_allele_freqs)\npop1_allele_freqs <- rbeta(M, shape1 = sh1, shape2 = sh2)\npop2_allele_freqs <- rbeta(M, shape1 = sh1, shape2 = sh2)\npop3_allele_freqs <- rbeta(M, shape1 = ((1-f_pop3)/f_pop3)*ancestral_allele_freqs, shape2=((1-f_pop3)/(f_pop3))*(1-ancestral_allele_freqs))\npop4_allele_freqs <- rbeta(M, shape1 = ((1-f_pop4)/f_pop4)*ancestral_allele_freqs, shape2=((1-f_pop4)/(f_pop4))*(1-ancestral_allele_freqs))\n\nall_allele_freqs <- list(pop1_allele_freqs, pop2_allele_freqs, pop3_allele_freqs, pop4_allele_freqs)\nnames(all_allele_freqs) <- paste0('population_', 1:4)\n```\n:::\n\n\n#### First, how does the expected value of the distribution of allele frequency changes as a factor of the $F_{ST}$? This should give us an idea of what to expect when we simulate allele frequencies. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# generate many Fst values\nfst_vector <- round(seq(0.01, 0.99, length.out=20), 2) # 20 fsts ranging from 0.01 to 0.99\nper_fst <- lapply(fst_vector, function(each_fst){\n  \n  sh1 <- ((1-each_fst)/each_fst)*ancestral_allele_freqs\n  sh2 <- ((1-each_fst)/(each_fst))*(1-ancestral_allele_freqs)\n  temp_allele_frq <- rbeta(M, shape1 = sh1, shape2 = sh2)\n  deviation <- cor(ancestral_allele_freqs, temp_allele_frq) #|> suppressWarnings()\n  return(deviation)\n})\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncor_deviation <- per_fst |> unlist()\n\nplot(cor_deviation, frame.plot=F, xaxt='n', yaxt='n', type='b', xlab = expression(F[ST]), ylab=expression(R^2))\naxis(1, at=rep(1:length(cor_deviation), by=1), labels = fst_vector, las=2)\naxis(2, at=seq(0, 1, 0.1))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nWe see that as the $F_{ST}$ increases, the correlation between the ancestral allele frequency and the generated allele frequency reduces. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlayout(matrix(c(1,2,3,4,5,6), nrow = 2, ncol = 3, byrow = T))\nnames_pop <- names(all_allele_freqs)\nfor(i in 1:4){\n    for(j in 1:4){\n        if(i == j){ # we don't want to plot pop1 vs pop1 e.t.c.\n            next\n        } else if (i < j) {\n            #cor_ <- round(cor(all_allele_freqs[[i]], all_allele_freqs[[j]]), 2)\n            plot(all_allele_freqs[[i]], all_allele_freqs[[j]], xlab = names_pop[i], ylab = names_pop[j], frame.plot = F)\n            #abline(a=0, b=cor_, col='red')\n            #mtext(cor_)\n        }\n    }\n}\nmtext('Scatterplot of allele frequencies for each population', outer = T)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/scatterplot allele frequencies-1.png){width=672}\n:::\n:::\n\n\nThe plot is approximately (roughly?) what we expect!\n\n## Simulating genotypes using these allele frequencies\nGiven these allele frequencies, we can simulate genotypes from each of these populations by sampling from a binomial distribution. \n\n\\begin{align}\nG_{k_{n}} \\sim Binom(n, p_{k})\n\\end{align}\n\nwhere $n$ is the number of success, and $p$ is the probability of a success. Here, $n = 2$ because we want 2 alleles per loci, and $p$ is the allele frequency at that loci. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ngenotypes <- lapply(seq_along(all_allele_freqs), function(i){\n    matrix(data=rbinom(n=N*M, size=2, prob = all_allele_freqs[[i]]), nrow = N, ncol = M, byrow = T)\n})\n\ngenotypes <- do.call(rbind, genotypes)\nshuffle <- sample(1:nrow(genotypes)) # I will shuffle the data\ngenotypes <- genotypes[shuffle, ]\npops <- rep(names(all_allele_freqs), each=N)\npops <- pops[shuffle] # shuffle pops too, since it tells me what populations the genotypes come from\n\ncat('Here is what the genotypes look like\\n')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nHere is what the genotypes look like\n```\n:::\n\n```{.r .cell-code}\ngenotypes[1:5, 1:5]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     [,1] [,2] [,3] [,4] [,5]\n[1,]    0    1    0    1    0\n[2,]    2    1    1    1    0\n[3,]    0    1    0    0    0\n[4,]    0    0    0    1    0\n[5,]    1    1    0    0    0\n```\n:::\n\n```{.r .cell-code}\ncat('And here is what the population designation looks like \\n')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnd here is what the population designation looks like \n```\n:::\n\n```{.r .cell-code}\npops[1:5]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"population_1\" \"population_2\" \"population_4\" \"population_3\" \"population_1\"\n```\n:::\n:::\n\n\nNext, we can calculate the principal components (PCs) of this data, and plot PC1 vs PC2, to see where the most variability lies in the data\n\n::: {.cell}\n\n```{.r .cell-code}\n# first change the row names of the genotype data to reflect the populations\n#rownames(genotypes) <- pops\n# I need to make sure that there are some variations in the SNPS - if there aren't any, I should remove them\npca_genotypes <- genotypes[ , which(apply(genotypes, 2, var) != 0)]\n# PCA\npca_dt <- prcomp(pca_genotypes, scale.=T, center=T)\npca_dt$x[1:5, 1:5]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n           PC1       PC2       PC3         PC4        PC5\n[1,] -1.995007 -4.371018 -6.261115 -2.04280387  0.4145112\n[2,] -4.641799 -5.295547  6.927820  0.65598991  1.9353612\n[3,] 12.633299  1.032694  0.190796  0.62104962  1.2281625\n[4,] -4.966141  8.160130 -1.044198  0.09739781 -0.2304617\n[5,] -2.995745 -6.397834 -6.001949 -0.58087101  0.2056421\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# colors\nmycolors <- colorRampPalette(RColorBrewer::brewer.pal(8, \"Dark2\"))(n_pops)\n#mycolors <- c('red', 'orange', 'green', 'blue')\ncolor_coding <- factor(pops, labels = mycolors)\nplot(pca_dt$x[, 'PC1'], pca_dt$x[, 'PC2'], bg=as.character(color_coding), xlab = 'PC1', ylab = 'PC2', frame.plot = F, pch=21, main='PC1 vs PC2 of 4 discrete populations')\nlegend('topleft', legend=names_pop, pch=c(21, 21, 21, 21), pt.bg=mycolors, bty = 'n', xpd=NA)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nWe can look at populations 1 and 2 only, and see if there is any difference between them. \n\n::: {.cell}\n\n```{.r .cell-code}\npop_names <- c('population_1', 'population_2')\nidx <- which(pops %in% pop_names)\npca_12 <- pca_dt$x[idx, ]\ncolor_coding <- factor(pops[idx], labels = mycolors[1:2])\nplot(pca_12[, 'PC1'], pca_12[, 'PC2'], bg=as.character(color_coding), xlab = 'PC1', ylab = 'PC2', frame.plot = F, pch=21, main='PC1 vs PC2 of the 2 similar populations 1 and 2')\nlegend('topleft', legend=pop_names, pch=c(21, 21), pt.bg=mycolors[1:2], bty = 'n', xpd=NA)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\n\n### Simulating continuous populations\nWhat I have done so far, is to simulate a discrete population of individuals. Think of it as people living in Mars, Earth, and Jupiter, and who have never intermingled since time immemorial. Population 3 is faraway from population 4. However, true human populations are not this way. How can we simulate a truly continuous population?\n\nFirst, notice that I am only simulating allele frequencies. Therefore, I can put a prior on my earlier-defined beta distribution to model the probability that an individual is from population $m$. In other words, I am trying to estimate what percentage of an individual's alleles might have come from a certain population $m$. I will call this random variable, $Q$. \n\n\\begin{align}\nQ \\sim Dirichlet(\\alpha)\n\\end{align}\n\nA trick I can use is to take an individual, ask how much of their genome is shared among each population I have, select that proportion of allele frequencies, and simulate their genotypes based on the selection for each population. To do this, I need to know how to distribute the $\\alpha$ parameter used in the Dirichlet distribution. A trick I can use is to use the allele frequency distribution in the entire population. I will call this distribution the population grade distribution. \n\nEarlier, I simulated some allele frequencies `all_allele_freqs`\n\n::: {.cell}\n\n```{.r .cell-code}\nss <- sapply(all_allele_freqs, sum)\npopulation_grade <- ss/sum(ss)\n#population_grade <- rand_vect_cont(4, 1)\npopulation_grade\n```\n\n::: {.cell-output .cell-output-stdout}\n```\npopulation_1 population_2 population_3 population_4 \n   0.2499524    0.2471564    0.2423278    0.2605634 \n```\n:::\n:::\n\n\nThen I can use this as a parameter to the Dirichlet distribution to simulate the percentage of an individual's genotypes that is shared across all 4 populations. \n\n::: {.cell}\n\n```{.r .cell-code}\nq_matrix <- gtools::rdirichlet(N * n_pops, alpha = population_grade) # I want to simulate, N individuals per population\n```\n:::\n\n\nHere is an illustration. Assuming that I am looking at the first individual\n\n::: {.cell}\n\n```{.r .cell-code}\n# assuming one individual\nid1 <- q_matrix[1, ]\nq_counts <- floor(id1 * M) # number of loci shared\nq_counts\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 370   0   4 125\n```\n:::\n:::\n\n\nThe assumption here is that this individual shares 370 loci with population 1, 0 with population 2, 4 with population 3, and 125 loci with population 4, and 3 independent loci not share with any population. The sum is 499 (because I rounded down), but I don't want this to be this case. Therefore, I will share the remaining loci with the highest number already available, so that the sum is 500.\n\n::: {.cell}\n\n```{.r .cell-code}\nremainder_ <- M - sum(q_counts)\nq_counts[which.max(q_counts)] <- q_counts[which.max(q_counts)] + remainder_\nq_counts\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 371   0   4 125\n```\n:::\n:::\n\nNow, this sums to 500.\n\nPutting this into a reusable function...\n\n::: {.cell}\n\n```{.r .cell-code}\nq_counts_fxn <- function(q_matrix, M){\n    apply(q_matrix, 1, function(each_row){\n        temp <- floor(each_row * M)\n        remainder_ <- M - sum(temp)\n        temp[which.max(temp)] <- temp[which.max(temp)] + remainder_\n        temp\n    }) |> t()\n}\n\nq_counts <- q_counts_fxn(q_matrix, M)\nq_counts[1:5, ] # for the first 5 individuals\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     [,1] [,2] [,3] [,4]\n[1,]  371    0    4  125\n[2,]    1  470    0   29\n[3,]  307  175    0   18\n[4,]  175  325    0    0\n[5,]  341  159    0    0\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ngenotypes <- matrix(NA, nrow = N*n_pops, ncol = M) # remember, N individuals per population\n\nfor(q in 1:nrow(q_counts)){\n    pop_down <- 1\n    m_loci <- 1:M\n    i_loci <- list() # this list contains the actual loci an individual has shared among the other populations\n    while(pop_down <= ncol(q_counts)){\n        # sample pop 1 loci\n        pop_loci <- sample(m_loci, size=q_counts[q, pop_down], replace = F)\n        if(length(pop_loci) == 0){\n            m_loci <- m_loci[m_loci != 0]\n            i_loci[[pop_down]] <- 0\n        } else {\n            m_loci <- m_loci[!m_loci %in% pop_loci]\n            i_loci[[pop_down]] <- pop_loci\n        }\n        pop_down <- pop_down + 1\n    }\n    \n    g_loci <- lapply(seq_along(i_loci), function(i){\n        temp <- all_allele_freqs[[i]][i_loci[[i]]]\n        rbinom(n = length(temp), size = 2, prob = temp)\n    })\n\n    gi <- vector(mode='numeric', length = M)\n    for(i in 1:n_pops){\n        gi[i_loci[[i]]] <- g_loci[[i]]\n    }\n    \n    genotypes[q, ] <- gi\n    \n}\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npop <- paste0('population_', apply(q_counts, 1, which.max))\n# first change the row names of the genotype data to reflect the populations\nrownames(genotypes) <- pop\n# I need to make sure that there are some variations in the SNPS - if there aren't any, I should remove them\npca_genotypes <- genotypes[ , which(apply(genotypes, 2, var) != 0)]\n# PCA\npca_dt <- prcomp(pca_genotypes, scale.=T, center=T)\npca_dt$x[1:5, 1:5]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                     PC1      PC2        PC3        PC4        PC5\npopulation_1 -0.09503535 3.618773  3.8529654 -0.5932727 -0.1152797\npopulation_2  2.59847249 2.996719 -7.9176185 -0.4884764 -1.7167200\npopulation_1  3.52834153 5.580367  0.8892966  1.2828101 -0.3694112\npopulation_2  4.22649950 5.754394 -1.9810583 -0.6000665  0.7466281\npopulation_1  1.09875913 5.734937  2.8937317  1.0117957 -0.7406395\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmycolors <- colorRampPalette(RColorBrewer::brewer.pal(8, \"Dark2\"))(n_pops)\ncolor_coding <- factor(rownames(pca_dt$x), labels = mycolors)\nplot(pca_dt$x[, 'PC1'], pca_dt$x[, 'PC2'], bg=color_coding |> as.character(), xlab = 'PC1', ylab = 'PC2', frame.plot = F, pch=21, main='PC1 vs PC2 of 4 continuous populations')\nlegend('topleft', legend=names_pop, pch=c(21, 21, 21, 21), pt.bg=mycolors, bty = 'n', xpd = NA)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/plotting continuous population-1.png){width=672}\n:::\n:::",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}